# Generated by Django 4.2.3 on 2024-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_cart_product_id_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
