# Generated by Django 4.2.3 on 2024-07-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_id',
        ),
    ]
